# bank2ynab configuration file

[DEFAULT]
# Specify where you save your downloaded CSV files:
Source Path = %USERPROFILE%\Downloads
# CHANGING ANYTHING BELOW THIS LINE WILL PROBABLY BREAK THINGS HORRIBLY. DON'T DO IT!
# Filename search
Source Filename Pattern = example_transaction_export_filename
Source Filename Extension = .csv
Use Regex for Filename = False
# Source file formatting
Source CSV Delimiter = ,
Header Rows = 1
Footer Rows = 0
Input Columns = Date,Payee,Outflow,Inflow,Running Balance
# (see https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes for date format strings)
Date Format =
Date De-Duplication = False
Inflow or Outflow Indicator =
Currency Conversion Factor = 1
Encoding  =
# Output file formatting
Output Columns = Date,Payee,Category,Memo,Outflow,Inflow
Output Filename Prefix = fixed_
Output Filename Extension = .csv
Use Payee for Memo = True
API Transaction Fields = account_id,date,payee_name,amount,memo,category,cleared,import_id
# Post-processing
Delete Source File = True
Save Output File = True
# Plugins
Plugin =
Plugin Arguments =
# YNAB API Stuff - don't modify values here, modify in user_configuration.conf
Save YNAB Account = True
YNAB API Access Token =
YNAB Account ID =

#####################################################################################################
# ADD CUSTOM BANKS BELOW.
# Just make a new [section heading] and copy only the lines from above that need a non-default value.
# Please keep this sorted alphabetically by [country + bank name] for easier maintenance.
#####################################################################################################

[DE Deutsche Kreditbank checking]
# source: Issue #132
# 1234567890.csv
Use Regex For Filename = True
Source Filename Pattern = [0-9]{10}
Header Rows = 7
Source CSV Delimiter = ;
Input Columns = skip,Date,Memo,Payee,skip,skip,skip,Inflow,skip,skip,skip
Date Format = %d.%m.%Y

[DE Deutsche Kreditbank checking new]
Use Regex For Filename = True
Source Filename Pattern = [0-9]{2}-[0-9]{2}-[0-9]{4}_Umsatzliste_[\S]*_DE[0-9]{20}
Header Rows = 5
Source CSV Delimiter = ;
Input Columns = skip,Date,skip,skip,Payee,Memo,skip,skip,Inflow,skip,skip,skip
Date Format = %d.%m.%y

[DE Deutsche Kreditbank credit card]
# source: Issue #132
# 1234________1234.csv
Use Regex For Filename = True
Source Filename Pattern = \d{4}_{8}\d{4}
Header Rows = 7
Source CSV Delimiter = ;
Input Columns = skip,skip,Date,Memo,Inflow,skip
Date Format = %d.%m.%Y
